name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install lcov
        run: sudo apt-get install lcov
      - name: Install cmake
        uses: lukka/get-cmake@v3.17.2
      - run: mkdir ./build
      - run: cmake .
      - run: make Chip8Emu_coverage
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
